package com.uptodd.uptoddapp.utilities

const val DEFAULT_HOMEPAGE_INTENT = -302
const val DAILY_ALARM_REQUEST_CODE = -101
const val WEEKLY_ALARM_REQUEST_CODE = -102
const val MONTHLY_ALARM_REQUEST_CODE = -103
const val ESSENTIALS_ALARM_REQUEST_CODE = -104
const val MONTHLY_SESSIONS_CHECK_ALARM_REQUEST_CODE = -121
const val DAILY_ACTIVITY_STATUS_CHECK = -151
const val DAILY_ACTIVITY_STATUS_CHECK_NOTIFICATION = -152
const val WISHES_REQUEST_CODE = -301
const val PRE_SALES_CODE = -350
const val WE_MISS_YOU_DOCTOR = -360
const val SUBSCRIPTION_NOTIFY_CODE = -400
const val DEFAULT_NOTIFICATION_ID = -401
const val WEEKLY_REFER_ALARM_REQUEST_CODE = -200
const val WEEKLY_PHOTO_ALARM_REQUEST_CODE = -201
const val WEEKLY_DOCTOR_REFER_ALARM = -250
const val WEEKLY_PATIENT_REFER_ALARM = -251
const val UPTODD_MEDIA_PLAYER_NOTIFICATION = -1500
const val DOCTOR_NO_REFERRAL = -370
